on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: angularcontainerregistry.azurecr.io
        username: ${{ secrets.acr_angularcontainerregistry_username }}
        password: ${{ secrets.acr_angularcontainerregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t angularcontainerregistry.azurecr.io/kubecluster:${{ github.sha }}
        docker push angularcontainerregistry.azurecr.io/kubecluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kubecluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kubeclustera168 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kubeclustera168`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kubeclustera168
        container-registry-url: angularcontainerregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_angularcontainerregistry_username }}
        container-registry-password: ${{ secrets.acr_angularcontainerregistry_password }}
        secret-name: kubeclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: kubeclustera168
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          angularcontainerregistry.azurecr.io/kubecluster:${{ github.sha }}
        imagepullsecrets: |
          kubeclusterdockerauth